/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef TEST_H
#define TEST_H

/* function declarations */
void init_Test(void);
Netsnmp_Node_Handler handle_GetTime;

#endif /* TEST_H */
